---
- hosts: pki-jenkins-fxx
  become: yes
  roles:
    # Install java if not available
    - geerlingguy.java

    # Install and configure Jenkins
    - installJenkins

    # Create pki-jenkins-bot build job
    - createBotBuildJob

    # Configure Travis py
    - configureTravisPy