---
- hosts: pki-jenkins-staging
  become: yes
  roles:
    # Install java if not available
    - geerlingguy.java

    # Install and configure Jenkins
    - installJenkins

    # Create pki-jenkins-bot build job
    - createBotBuildJob